### ISSUE TITLE
Any GUI support available?

### ISSUE THREAD

**Issue by mberlanda** [smoser/pdftk#10]
Dear team,

thank you very much for maintaining pdftk. There is any plan to introduce a gui for the command-line utility?
My wife is using my laptop to scan documents and she does not want to learn how to use the terminal.

I have already spent almost two years trying to teach it and now I hesitate to give up.
Can you point me to some interfaces?

I shown how great is a simple

```
$ pdftk --help

       Remove page 13 from in1.pdf to create out1.pdf
	 pdftk in.pdf cat 1-12 14-end output out1.pdf
	 or:
	 pdftk A=in1.pdf cat A1-12 A14-end output out1.pdf
```

but she refuses to read it :smile:

**Comment by smoser** [comment]
Hi, sorry. this is just a snap version of the pdftk application. I don't do any work on it.  You could request that feature upstream.  https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/ . it looks like there *is* a gui there.
