### ISSUE TITLE
What is the difference?

### ISSUE THREAD

**Issue by Foorack** [smoser/pdftk#2]
Between:

https://snapcraft.io/pdftk-smoser

and 

https://snapcraft.io/pdftk

**Comment by smoser** [comment]
There is no functional difference.
Originally I made a snap named 'pdftk-smoser' as I had not requested the 'pdftk' namespace.  Subsequently I requested the 'pdftk' name and published a snap under that name.

I have updated https://snapcraft.io/pdftk-smoser to make this clear.

At some point I will probably pubilsh an update to the 'pdftk-smoser' snap that suggests users get pdftk instead.

Sorry for the confusion.
