### ISSUE TITLE
cannot change current working directory to the original directory: Permission denied

### ISSUE THREAD

**Issue by ghost** [smoser/pdftk#4]
```
xxx@mimas:~$ sudo snap install pdftk
pdftk 2.02-4 from Scott Moser (smoser) installed
xxx@mimas:~$ pdftk 
cannot change current working directory to the original directory: Permission denied
```
Under Ubuntu 18.04.1 LTS  it does not work in a mounted (encfs encrypted) filesystem; works under my local home :(

PS.: Just unmounted the file system and remounted and now it works ...

**Comment by smoser** [comment]
Duplicate of #1

**Comment by smoser** [comment]
Please feel free to re-open if you think my diagnosis is wrong.
