### ISSUE TITLE
cannot change current working directory to the original directory: No such file or directory

### ISSUE THREAD

**Issue by trevor87** [smoser/pdftk#5]
Hi!

Thanks for providing pdftk for 18.04! I just installed the snap, but I get this error message when I execute pdftk:
`cannot change current working directory to the original directory: No such file or directory`

Do you have any idea where this comes from?

Greetings

**Comment by smoser** [comment]
Hi,
this is really a duplicate of issue 2.
Snaps do not have access to all directories.

Try using pdftk from your home directory.

re-open if you have issues.

**Comment by smoser** [comment]
Sorry, duplicate of #1
