### ISSUE TITLE
pdftk fails to exec

### ISSUE THREAD

**Issue by notklaatu** [smoser/pdftk#6]
On Fedora 28, I've installed both `hello` as a test and `pdftk`. The first executes successfully, the latter fails.

    $ head -n 2 /etc/os-release
    NAME=Fedora
    VERSION="28 (Twenty Eight)"
    $ sudo dnf install -y snapd
    [ ... ]
    $ sudo systemctl start snapd
    $ sudo snap install hello
    [ ... ]
    $ hello
    bash: hello: command not found
    $ /var/lib/snapd/snap/hello/20/bin/hello
    Hello, World!
    $ sudo snap install pdftk
    [ ... ] 
    $ /var/lib/snapd/snap/pdftk/9/usr/bin/pdftk 
    bash: /var/lib/snapd/snap/pdftk/9/usr/bin/pdftk: No such file or directory
    $ sudo chmod +x /var/lib/snapd/snap/pdftk/9/usr/bin/pdftk 
    Error blah blah: Read-only file system

This is my first experience with snap, so I may be overlooking a step, but given that hello works, I'm assuming pdftk ought to work in the same way, even if I do have to add /var/lib/snapd/snap/ to my PATH. But maybe there's some other path I need to add?

**Comment by smoser** [comment]
Snap programs should be executed out of /snap/bin .  I'm not sure how that would get added to your path on fedora.

Does it work if you add that to PATH and use it there?

**Comment by notklaatu** [comment]
There is no /snap directory on my system, after having installed with the steps shown above. Maybe this is a larger bug with the snap install, or the snap RPM.

**Comment by notklaatu** [comment]
Cool, it seems to be working now.

Following your lead, I did this:

    $ sudo ln -s /var/lib/snapd/snap /snap

And now I can execute by providing the full path to the executable:

    $ /snap/pdftk/9/usr/bin/pdftk --version
    pdftk 2.02 a Handy Tool for Manipulating PDF Documents
    Copyright (c) 2003-13 Steward and Lee, LLC - Please Visit: www.pdftk.com
    This is free software; see the source code for copying conditions. There is
    NO warranty, not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

So I'm closing this issue as resolved. Now to look into who owns the snap RPM so I can report the install bug.

Thanks for the snap package! pdftk isn't supported on Fedora any more, apparently, so this snap package is going to make my life a lot easier. Cheers!
