### ISSUE TITLE
Cannot download pdftk via snap; server feeds few bytes and resets

### ISSUE THREAD

**Issue by AncientZygote** [smoser/pdftk#9]
On Ubuntu 18.04.4 tried install pdftk from Ubuntu Software and it couldn't obtain the file. I watched it in system monitor and the server was simply not responding (sporadic couple of hundred bytes separated by long pauses). Same behavior with terminal session:
(base) dalton@dalton-Precision-3541:~$ sudo snap install pdftk
[sudo] password for dalton: 
error: cannot perform the following tasks:
- Download snap "pdftk" (9) from channel "stable" (Get https://canonical-lcy01.cdn.snapcraft.io/download-origin/canonical-lgw01/LTZvYybwMaNBk5uA3k1lN6ycmsAZq82i_9.snap?token=1589655600_db6ee88fe57ec561e5c7589ff0164a1867f3c328&interactive=1: read tcp 192.168.1.179:46212->91.189.88.178:443: read: connection reset by peer)

What's going on?

**Comment by smoser** [comment]
if this is still an issue, raise with snap i think. its probably not related to this specific snap.
